CREATE TABLE Cards (
Id INT PRIMARY KEY IDENTITY,
WordEn NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
WordRu NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
[Url] NVARCHAR(250) NOT NULL DEFAULT 'Unknown',
Transcript NVARCHAR(250) NOT NULL DEFAULT 'Unknown',
Deleted BIT DEFAULT 0);
go

CREATE TABLE Users (
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
[Address] NVARCHAR(150) NOT NULL DEFAULT 'Unknown',
IsAuth BIT NOT NULL DEFAULT 0,
Deleted BIT DEFAULT 0);
go

CREATE TABLE Results (
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
Result NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
CardRightId INT,
FOREIGN KEY (CardRightId) REFERENCES Cards (Id),
CardWrongId INT,
FOREIGN KEY (CardWrongId) REFERENCES Cards (Id),
UserId INT,
FOREIGN KEY (UserId) REFERENCES Users (Id),
Deleted BIT DEFAULT 0);
go

CREATE TABLE Dictionary(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
Result NVARCHAR(50) NOT NULL DEFAULT 'Unknown',
CardId INT,
FOREIGN KEY (CardId) REFERENCES Cards (Id),
UserId INT,
FOREIGN KEY (UserId) REFERENCES Users (Id),
Deleted BIT DEFAULT 0);
go

